name: Run speedlify

on:
  push:
  schedule:
    - cron: "0 0 */14 * *" # Run every 14 days at midnight UTC
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout speedlify and results
        uses: actions/checkout@master
        with:
          path: default

      - name: Copy existing results
        if: steps.checkout-results.outcome == 'success'
        run: cp -r results/. default/_data

      - name: Install npm dependencies
        run: npm ci
        working-directory: default

      - name: Run test-pages
        run: npm run test-pages
        working-directory: default

      - name: Push results
        run: |
          cp -r default/_data/results* results
          git -C results add .
          git -C results commit -m "Update results"
          git -C results push origin results
